---
title: "Course Project - Brazilian Capitals"
author: "Silva, Rafael"
date: "September 12, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction

I gathered some information about the states of my country, the objective of this document is to display them in a map done using leaflet. The chunk below shows the list of packages used to create this document, as well as the function used to read the dataset into R.
```{r, message=FALSE}
library(leaflet)
data <- read.csv("data/brazilianStates.csv")
head(data)
```

This document was created in:
```{r}
Sys.Date()
```

## Map

```{r, echo=FALSE}
df <- data[,4:5]

popup <- with(data, paste("<a href='", page, "'>", state, 
                        "<br>Abreviation: ", abrev, 
                        "<br>Capital: ", capital, sep = ""))

icon <- makeIcon("data/icon.png", iconWidth = 37.89, iconHeight = 49.32, 
                 iconAnchorX = 42.1/2, iconAnchorY = 54.8)

df %>%
    leaflet() %>%
    addTiles() %>%
    addMarkers(popup = popup, icon = icon)
```